/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gro' at '9/17/15 8:42 AM' with Gradle 2.6
 *
 * @author gro, @date 9/17/15 8:42 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
